-- require('core.plugin_config.gruvbox')
require('plugins.catppuccin')
require('plugins.lualine')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.telescope-ui-select')
require('plugins.indent-blankline')
require('plugins.spellrotate')
require('plugins.markdown-preview')
require('plugins.lsp-config')
require('plugins.none-ls')
